### ISSUE TITLE
Make first rough design UI and UX

### ISSUE THREAD

**Issue by devRabbani** [canwebe/SaITFeedBack#1]
# As discussed we will first make rough design

- [x]  **1st Design**
 - [x]  **Design is Good**

**Comment by devRabbani** [comment]
I am researching about this.

**Comment by MOHD-STREAM** [comment]
I will run some ideas and send by tonight

**Comment by devRabbani** [comment]
Okkk @MOHD-STREAM

**Comment by devRabbani** [comment]
I did it

**Comment by MOHD-STREAM** [comment]
Can we try altering the appearance of it

**Comment by devRabbani** [comment]
No time up
