### ISSUE TITLE
Need Teacher details

### ISSUE THREAD

**Issue by devRabbani** [canwebe/SaITFeedBack#10]
Collect teacher information from routine in json format

**Comment by Mohd-Zahid-01** [comment]
Need the format of the data is required in @devRabbani

**Comment by Mohd-Zahid-01** [comment]
Need 1 json file for each section right? @devRabbani

**Comment by devRabbani** [comment]
Only write it in white paper and submit it to the whatsapp group

**Comment by devRabbani** [comment]
Done by me
